vars: coreKubicProjectHousekeeping: Do not fail if not triggered by PR
If the job is triggered via regular schedule instead of PR, the
pullRequest object does not exist and it fails as follows:

groovy.lang.MissingPropertyException: No such property: pullRequest for class: coreKubicProjectHousekeeping
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
...

As such, only try to examine that object if we are trully running as
part of a PR.